import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

import { ConvexClientProvider } from "@/providers/convex-client-provider";

import { JotaiProvider } from "@/providers/jotai-provider";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={GeistSans.className}>
        <ConvexClientProvider>
          <JotaiProvider>
            {children}
          </JotaiProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
