import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

import { ConvexClientProvider } from "@/providers/convex-client-provider";

import { ThemeProvider } from "@/components/theme-provider";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", geist.variable)}>
      <body
        className={cn(GeistSans.className, "min-h-screen bg-cover bg-center bg-no-repeat bg-fixed relative")}
        style={{ backgroundImage: "url('/bg-meadow.jpg')" }}
      >
        <div className="fixed inset-0 bg-background/30 backdrop-blur-[1px] pointer-events-none z-[-1]" />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
